from setuptools import setup, find_packages

setup(
    name="google_cloud_utils",
    version="0.3.2",
    packages=find_packages(),
    install_requires=[
        "google-cloud-bigquery",
        "google-cloud-storage",
        "google-cloud-secret-manager",
        "google-cloud-tasks",
        "google-cloud-scheduler",
        "google-cloud-datastore",
        "google-cloud-firestore",
        "google-cloud-resource-manager",
        "google-cloud-aiplatform",
        "google-cloud-pubsub",
        "google-cloud-run",
        "google-cloud-core",
        "google-auth",
        "google-genai",
        "gspread",
        "protobuf",
        "requests",
        "tenacity",
        "pandas",
        "openpyxl",
        "numpy",
        "regex",
        "genson",
        "python-dotenv",
    ],
    author="DataGem Consulting",
    description="A wrapper for Google Cloud services handlers",
    python_requires=">=3.8",
)
#